# Generated by Django 4.2 on 2023-05-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='access',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=7),
        ),
    ]
