# Generated by Django 4.2 on 2023-05-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posted_in',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='posted_in',
            new_name='post',
        ),
    ]
